[package]
name = "tg-monitor-lizard"
version = "0.1.0"
edition = "2021"
authors = ["Lennard Brinkhaus <lennard.brinkhaus@dragse.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
